
USE [dbName]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [CATEGORIE](
	[ID_CATEGORIE] [int] IDENTITY(1,1) NULL,
	[NAME] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CATEGORIE_1] PRIMARY KEY CLUSTERED 
(
	[ID_CATEGORIE] ASC
)
) GO


CREATE TABLE [PRODUCT](
	[ID_PRODUCT] [int] IDENTITY(1,1) NULL,
	[NAME] [varchar](50) NOT NULL,
	[DESCRIPTION] [varchar](150) NOT NULL,
	[DATE_SAISIE] [datetime] NULL,
	[QUANTITE] [int] NOT NULL,
	[ID_CATEGORIE] [int] NOT NULL  CONSTRAINT PRODUCT_CATEGORIE__fk REFERENCES CATEGORIE,
    CONSTRAINT [PK_PRODUCT_1] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUCT] ASC
)
) ON [PRIMARY]
GO

ALTER TABLE [PRODUCT] ADD  CONSTRAINT [DF_PRODUCT_DATE_SAISIE]  DEFAULT (getdate()) FOR [DATE_SAISIE]
GO


INSERT INTO CATEGORIE VALUES ('CATEGORIE A')
INSERT INTO CATEGORIE VALUES ('CATEGORIE B')
INSERT INTO CATEGORIE VALUES ('CATEGORIE C')
INSERT INTO CATEGORIE VALUES ('CATEGORIE D')
INSERT INTO CATEGORIE VALUES ('CATEGORIE E')
INSERT INTO CATEGORIE VALUES ('CATEGORIE F')
INSERT INTO CATEGORIE VALUES ('CATEGORIE J')



